solarcity: parametrize logs and make other stuff optional
the-mace/evtools pull request #3
Opened 2019-05-17 18:29 UTC by 7AC

This unblocks the following command

```
DEBUG_MODE=1 SOLARCITY_PASSWORD=xxx SOLARCITY_USER=xx@xx.xx LOGFILE=logs/solarcity.log DARKSKY_API_KEY=xxx ./solarcity.py --report --no_email --no_tweet
```

I do still get an empty report though so I wonder if something is already broken:

```
Would email message:
Hi there, below is the weekly SolarCity generation report:

Total production this week: 0.0 kWh
Total production in the last 30 days: 0.0 kWh
Total production in the last 365 days: 0.0 kWh

Lifetime generation is 0.0 kWh.

Regards,
Teslaliving
http://teslaliving.net
```

2019-05-17 20:47 UTC, the-mace commented
Does the DATA_FILE have contents? ('solarcity.json') and is it in the directory you're running in? Without that and without contents the outputs would be all zero. 

(its running fine for me in my environment so this is likely a local ENV type difference again as in the changes above)

2019-05-17 22:00 UTC, 7AC commented
@the-mace thanks I don't. What do I need to put in it?

2019-05-19 20:23 UTC, the-mace commented
> @the-mace thanks I don't. What do I need to put in it?

Nothing, if you do a successful poll it will create a "solarcity.json" file for you. I just ran with no existing file and saw one bug which I fixed and pushed up. With that fix it will poll and leave a working file.

This is my complete file after a run from no file:
`{"config": {"lastdailytweet": "20190519"}, "data": {"20190519": {"daylight": 14.7, "cloud": 36, "production": 40.8}}}`

2019-05-20 19:10 UTC, 7AC commented
Thank you. I retried with your commit but I still get all zeros with the above command

2019-05-21 07:11 UTC, the-mace commented
> Thank you. I retried with your commit but I still get all zeros with the above command

There wont be any data until you run a --daily poll, did you do that?

2019-05-21 17:02 UTC, 7AC commented
Thank you that worked after a couple more tweaks that I added to the PR: https://github.com/the-mace/evtools/pull/3/commits/0bb9f7a3d5455e9e7dcecd94950bfc99842ad9ab

2019-08-04 15:48 UTC, the-mace requested changes

2019-08-04 15:48 UTC, the-mace commented on solarcity.py
> +            if args.pvoutput is not None:
This changes the behavior. If you provide "--pvoutput" a parameter it ONLY sends output to pvoutput. If you do daily it does the daily stuff and the output to pvoutput. Could re-order the parsing to catch daily first or solve it another way.

2019-08-04 15:48 UTC, the-mace commented on solarcity.py
> +LOGFILE = os.environ.get('LOGFILE')
Probably could use a better name here. SOLAR_LOGFILE maybe. LOGFILE could pick up something else.

2019-08-25 20:15 UTC, merged

2019-08-25 20:15 UTC, the-mace commented
Merged it but Tesla took SolarCity page offline so this whole script wont work any more :(

2019-08-25 20:17 UTC, stephenjamieson commented
https://solarguard.solarcity.com/Kiosk/Login/Default.aspx dunno why this site is still around (probably abandoned) but check it out....  Otherwise check out https://github.com/jbuehl/solaredge